@startuml

Животное -up-{ "Значение индикатора"
Индикатор --{ "Значение индикатора"
"Единица измерения" --{ "Значение индикатора"
"Возможное значение качественного индикатора" --{ "Значение индикатора"
"Вид животного" -l-{ Животное
Пол -l-{ Животное
Животное -l-{ Файл
"Тип файла" --{ Файл

class Животное {
    +Идентификатор
    -Кличка
    -Дата рождения
    -Краткое описание
    -Полное описание
}

class "Вид животного" {
    +код
    +наименование
    -описание
}

class "Пол" {
    +код
    +наименование
    -описание
}

class "Файл" {
    +номер
    +дата
    +URL файла
    -наименование
    -описание
}

class "Тип файла" {
    +код
    +расширение
    +наименование
}

class "Индикатор" {
    +код
    +наименование
    +признак качественного индикатора
    -описание
}

class "Единица измерения" {
    +код
    +наименование
    -краткое наименование
}

class "Возможное значение качественного индикатора" {
    +код
    +наименование
    +значение
}

class "Значение индикатора" {
    +номер
    +дата
    +коэффициент важности
    +значение
}

@enduml
