@startuml

"Тип животного" --{ Животное
"Пол животного" --{ Животное
"Индикаторы состояния животного" -- Животное
"Индикаторы состояния животного" }-- "Контейнер критериев"
"Животное" -- "Контейнер критериев"
"Контейнер критериев" -- "Отчет"

class Животное {
    +Идентификатор
    +Кличка
    +Дата рождения
    +Краткое описание
    +Полное описание
    +Ссылка на изображение
    +Дата создания записи
    +Дата последнего обновления
    +Тип животного
    +Пол животного
    +Индикаторы состояния
}

class "Тип животного" {
    +Идентификатор
    +Наименование
    +Описание
    +Ссылка на изображение
}

class "Пол животного" {
	+Идентификатор
	+Наименование
	+Описание
	+Ссылка на изображение
}

class "Индикаторы состояния животного" {
  +Идентификатор
  +Возраст
  +Размер (высота в холке)
  +Частота дыхания
  +Частота сердцебиений (ЧС)
  +Температура тела
  +Количество сильных повреждений
  +Количество слабых повреждений
  +Количество симптомов заболеваний
  +Признак младенческого возраста
  +Наличие сознания 
  +Наличие кровотечения
  +Признак со-хранения мобильности
  +Степень аппетита
  +Наличие беременности
  +Степень стресса и агрессии
}

class "Контейнер критериев" {
  +Животное
  +Список индикаторов состояния животного до нормализации
  +Список индикаторов состояния животного после нормализации
  +Список индикаторов состояния животного после взвешивания
  +Итоговый критерий
}

class "Отчет" {
  +Список контейнеров критериев
}

@enduml
