@startuml

left to right direction
:**Неавторизованный пользователь**: -up-> (**Просмотр информации на сайте**)

:**Пользователь-волонтер**: -up-> (**Просмотр информации на сайте**)
:**Пользователь-волонтер**: -up-> (**Вход в систему**)
:**Пользователь-волонтер**: -up-> (**Ввод, обновление, удаление информации о животных**)
:**Пользователь-волонтер**: -up-> (**Формирования Списка животных для оценки**)
:**Пользователь-волонтер**: -up-> (**Формирование Отчета по оценке состояния животных**)

@enduml
