vars:
  api:
    version-url: /api/v1
    info:
      title: Panda server
      description: Spring Boot backend for Panda
  startup:
    init-sample-data: true
  animal-indicator-weights:
    age: 0.3
    is-infant: 0.6
    consciousness-level: 1.0
    height: 0.5
    breathing-rate: 0.8
    heart-rate: 0.8
    bleeding-level: 0.9
    body-temperature: 0.8
    severe-damage-count: 0.9
    mild-damage-count: 0.7
    mobility-loss-level: 1.0
    appetite-level: 0.8
    has-symptoms: 0.8
    is-pregnant: 0.3
    aggression-level: 1.0
springdoc:
  api-docs:
    enabled: true
    resolve-schema-properties: true
  swagger-ui:
    enabled: true
    deepLinking: true
    validator-url: none
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: panda
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        default_schema: panda
        hbm2ddl:
          charset_name: UTF-8
  flyway:
    enabled: true
    schemas: panda
    default-schema: panda
logging:
  charset:
    console: UTF-8
  ###level:
    ### log just the SQL org.hibernate.SQL: DEBUG
    ### log JDBC bind parameters org.hibernate.type: TRACE org.hibernate.type.descriptor.sql: TRACE